### PR TITLE
Pr/13

### PR DESCRIPTION
**Pull request by angusmcleod**
@fzngagan I've made a few changes to your work before I bring it in, starting with the client-side. Here's what I'm changing client-side in this commit: https://github.com/angusmcleod/discourse-custom-wizard/commit/ee717197930a1cc9cfed618b3a42206190534ba2.

1. The logic in the admin view needed to be tightened a bit. For example
    - There were a number of different properties for displaying error messages to the user. These need to be consolidated into a single property. As much as possible try to abstract functionality into computed properties in the controller or component javascript. Keep the templates as short and expressive as possible.

    - The logs needed to be combined and structured for a unified display.

2. Some code was not necessary. For example ``filePath`` does not need to be an array. 

4. More formatting changes:
   - Locale keys must be underscored (i.e. keys in client.en.yml).
   - Element ids and classnames must be hypenated.
   - Keep code line length below 80 chars when possible. 

5. I made a few other tweaks, including add a title for the logs indicating what they are logs of.

Whenever you delve into a new framework, codebase and way of working there's always many different little things to learn, so happy to help out in more detail at this stage. Let me know if you have any question about the changes I've made. 

I'm going to take a closer look at the server-side as well before merging.

### CODE REVIEW

**Comment by fzngagan** [comment]
Hey @angusmcleod, I read the code changes you made and you did it really elegantly. I could make it work but I see there's a lot to learn and understand. I'll keep each of these patterns in mind for the work I do further.

**Comment by angusmcleod** [comment]
@fzngagan A few more changes here: https://github.com/angusmcleod/discourse-custom-wizard/pull/14/commits/922afdc1bde5aaa032594d13ecff731dfcbe5869

1. We need to also clear the file from the input when there is a client-side error. I made a few other client-side tweaks as well concerning the error messages.

2. Server-side, logic-wise we can just have a single begin...rescue block where we parse the JSON and catch any errors. No need to first validate the json and then parse for a second time. Note also that you should always rescue specific errors, e.g. JSON::ParserError, not all errors. See https://stackoverflow.com/questions/10048173/why-is-it-bad-style-to-rescue-exception-e-in-ruby

3. If CustomWizard::Template.new(o) fails we need to add the wizard to the failed_ids

**Comment by angusmcleod** [comment]
@fzngagan Finally, I've componentized the import and export client-side code, i.e. put import and export client-side code into their own components.: https://github.com/angusmcleod/discourse-custom-wizard/pull/14/commits/c156dcb6d14e1b0489dbc801cf04787893882bc6

There are a few reasons this makes sense:

1. It makes it easier to read the code.

2. Components initialize computed properties when rendered, this means that if there is any data in the view (e.g. checkboxes selected, or messages showing) they will not persist if you navigate to another view and then navigate back. If the properties are on the controller they will persist as the controller keeps its state in memory.

@fzngagan Ok, I think we're ready to merge. Anything else you want to add before we merge?

**Comment by fzngagan** [comment]
Only one thing I have in mind. Is it possible that someone bypasses client size validation and manages to have a huge file uploaded on the server even though its momentarily?

**Comment by angusmcleod** [comment]
@fzngagan Yeah, it's possible. However you've ensured they're an admin and you also have a server-size size check so I'm fine with that.

**Comment by fzngagan** [comment]
> 2\. Components initialize computed properties when rendered, this means that if there is any data in the view (e.g. checkboxes selected, or messages showing) they will not persist if you navigate to another view and then navigate back. If the properties are on the controller they will persist as the controller keeps its state in memory.

I didn't know that. I'll read about it in detail.

> Yeah, it's possible. However you've ensured they're an admin and you also have a server-size size check so I'm fine with that.

Yeah, that's correct.

**Pull request merged**
